
data_name: "custom6" # Your data folder will be "data/data_name/"
 # class names of the target objects
labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109']

yolo_layer_number: 3 # 1 or 2 or 3. By default it's 3.

img_aug_nums:
# Format: [l, r] means uniformly select a value between [l, r] implicitly.
  "num_new_images": 2000 # How many training images with labels we want to generate
  "objects_per_image": [3, 3] # How many objects per image

yolo:
  "ratio_train": 0.8 # percentage of images for training (in "train.txt"); The rest goes into "valid.txt".

yolo_inference:
  "conf_thres": 0.95 # object confidence threshold
  "nms_thres": 0.5  # iou thresshold for non-maximum suppression
  "batch_size": 1 # size of the batches   when reading images. Used in src/detect_images.py
  "n_cpu": 4      # number of cpus to use when reading images. Used in src/detect_images.py
  "img_size": 416 # size of each image dimension. 
                  # WARNING: Currently the image must be a square. 
                  # What's worse, the setting for img_size is in a chaos (It's set in multiple places). 
                  # If you want to change image size, you need to search for all (e.g. 416) and replace them all. 
                  
template_aug_effects: 
  "rela_size" :  [0.03, 0.15] # template's relative size wrt background image
  "rescale" : [1.0, 1.8] # rescale template
  "rotation" : [-90, 90] # rotate template
  "shear" : [-0.25, 0.25] # shear template
  "translate_x" : [0, 1] # translate template on the background image.
  "translate_y" : [0, 1] #    (x=0, y=0) is left-up, and (x=1, y=1) is bottom-right corner
  "brightness_offset" : [-30, 30] # inc/decrease the brightness of template image

# -- Others

# For the data augumentation of background images, please directly modifty: 
#  script: "utils/lib_augment_image.py"
#  function": "def _set_args_for_background_augment"

# For the configurations of file paths, please directly modify:
#  script: "config/config.py"
#  function: "def set_fixed_arguments"
